[package]
name = "sha2-256-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_02_02" }

[dev-dependencies]
ethers-core = "^1.0.0"
